---
# tasks file for download-untar
- name: download-untar - tmp download directories
  file:
    path: /tmp/downloads/
    state: directory
    mode: '0755'

- name: download-untar - Create destination directories
  file:
    path: '{{ item.dest }}'
    state: directory
    mode: '0755'
  loop:
    '{{ download }}'

- name: download-untar - Download tar files
  get_url:
    url: '{{ item.url }}'
    dest: '{{ "/tmp/downloads/" + item.url.split("/")[-1] }}'
  loop:
    '{{ download }}'

- name: download-untar - Extracting etcd files
  unarchive:
    src: '{{ "/tmp/downloads/" + item.url.split("/")[-1] }}'
    dest: '{{ item.dest }}'
    remote_src: true
  loop:
    '{{ download }}'

- name: download-untar - Cleaning downloaded files
  file:
    path: '/tmp/downloads/'
    state: absent
